name: fanni_app
description: تطبيق خدمات فنية - واجهة عملاء وفنيين مع حجز وخريطة ودردشة وتقييمات وإشعارات FCM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
